apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: dev
  labels:
    app: backend
spec:
  selector:
    app: backend-deployment
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
