apiVersion: v1
kind: Service
metadata:
  name: patient-frontend-service
  namespace: dev
  labels:
    app: patient-frontend-service
spec:
  selector:
    app: frontned-deploy
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: LoadBalancer
