apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs
  namespace: dev
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce # Or ReadWriteMany if your applications support it and you configured the NFS export for it
  persistentVolumeReclaimPolicy: Retain # Or Retain/Delete based on your preference
  storageClassName: ""
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /exports/kubernetes_nfs_pv # This is the directory you created and exported
    server: your ip          # This is the IP address of your NFS server
